### ISSUE TITLE
Use biblatex to filter references

### ISSUE THREAD

**Issue by dpertin** [barraq/pandoc-moderncv#15]
Hello,

Firstly, thanks for this great project :)

I am designing my CV, and since I work in a research context, I want to embed my own references within a specific section. [Biblatex](https://www.ctan.org/pkg/biblatex), which seems to be the best solution for it, as it is able to filter references from a .bib file, relies on latex.

I need to add some rules in the .tex header to set the biblatex filters (see [this example](http://tex.stackexchange.com/questions/28509/biblatex-filter-out-publications-from-a-specific-author-in-the-references-dynam#answer-28555)).
As far as I understood (but my knowledge is limited), pandoc-moderncv does not rely on a latex template. 

Any ideas?

**Comment by barraq** [comment]
Hi @denaitre, indeed Pandoc-ModernCV does not rely on Latex but HTML template. The main reason is that its focus is to generate both nice looking PDF easily (no use of crazy tex templating but rather simple HTML+CSS) and responsive HTML export. If you need a more Latex oriented tool I rather recommend you to use the original ModernCV package.

Nevertheless it is not hard to automatically generate a markdown friendly export of your BibTex in order to append it at the end of your CV. Actually it is what I did for my (old) research CV: http://remibarraquand.com/static/documents/contact/remi_barraquand_cv.pdf
You might find some answer on how to do that here:
- http://stackoverflow.com/questions/13545725/automatically-create-citations-list-for-personal-academic-site-from-bibtex
- https://gist.github.com/dsanson/1182008

Hope that helps ;)

Let me know of your progress, I guess we could add such a feature in next version of Pandoc-ModernCV.

Best,
