### ISSUE TITLE
sass conflict between susy and compass

### ISSUE THREAD

**Issue by jniggemann** [barraq/pandoc-moderncv#7]
I get an error when I issue `make html`, see below, may be due to different sass versions that get installed when installing susy and compass.

```
$ make html
rsync -rupE fonts dist
rsync -rupE cv/images dist
compass compile \
          --require susy \
          --sass-dir stylesheets \
          --javascripts-dir javascripts \
          --css-dir dist/stylesheets \
          --image-dir cv/images \
          stylesheets/style.scss
Gem::LoadError on line ["1637"] of /usr/lib/ruby/1.9.1/rubygems/specification.rb: Unable to activate susy-2.1.3, because sass-3.2.19 conflicts with sass (< 3.5, >= 3.3.0)
Run with --trace to see the full backtrace
make: *** [style] Error 1
```

No use in uninstalling either version of sass, as either compass or susy depend on them:
compass-0.12.7 depends on [sass (~> 3.2.19)]
susy-2.1.3 depends on [sass (< 3.5, >= 3.3.0)]

**Comment by jniggemann** [comment]
using compass-susy-plugin doesn't help either, but it seems installing compass --pre does:
`gem install compass --pre`

**Comment by barraq** [comment]
Hi @jniggemann indeed Susy >2.1 requires Sass 3.3.0 which is not compatible with Compass 0.12 :/ It is therefore required to install Compass with the --pre option... 
Compass 0.12 has been there for sooo long... I was hoping they will release Compass 0.13 or the new Compass 1.0 version sooner but it is taking more time than expected...

Anyway, I'll add it to the doc ;) Thanks for pointing it out :)

When I get a bit of time I will put the generated Stylesheets on the repo so that you will not have to install Susy nor Sass nor Compass unless you want to customize the themes.

Best,
Rémi
